# Overview

The following notebook supports a study of classifier methods used in contemporary machine learning. This specific experiment provides python implementations as a basis for comparisons of performance using the same dataset and evaluation criteria. This is by no means exhaustive, but illustrative in the differences between each method, and informative in which perform better on different types of data.

# Data

The data being used for this experiment is part of the sci-kit package, the 20 newsgroups dataset that contains 18000 newsgroups posts on 20 topics. Like the MNIST dataset it comes cleansed, labeled, and packaged with sci-kit. It also has a vectorized set available which include features that are ready to use with classifiers.

In [1]:
#Examine categories
from sklearn.datasets import fetch_20newsgroups
textdata = fetch_20newsgroups(subset='train')
print(list(textdata.target_names))

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


For convenience scikit has a dataset that is already vectorized. It is leveraged throughout this experiment. 

In [2]:
from sklearn.datasets import fetch_20newsgroups_vectorized
data = fetch_20newsgroups_vectorized('all')

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
newsdata = data
X = newsdata.data
y = newsdata.target

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y, test_size=0.1)

In [6]:
X_train.dtype

dtype('float64')

In [7]:
X_train

<16961x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 2602382 stored elements in Compressed Sparse Row format>

In [8]:
X_train.shape

(16961, 130107)

In [9]:
y_train.dtype

dtype('int64')

In [10]:
y_train.shape

(16961,)

# Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
logregress = LogisticRegression(solver = 'lbfgs')

In [12]:
logregress.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='lbfgs', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
logregress_predictions = logregress.predict(X_test)

In [14]:
logregress_score = logregress.score(X_test, y_test)
print (logregress_score)

0.820689655172


In [15]:
logregress2 = LogisticRegression(solver = 'sag')

In [16]:
logregress2.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='sag', tol=0.0001,
          verbose=0, warm_start=False)

In [17]:
logregress_predictions2 = logregress2.predict(X_test)

In [18]:
logregress_score2 = logregress2.score(X_test, y_test)
print (logregress_score2)

0.820689655172


In [19]:
#Additional performance measures
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(classification_report(y_test, logregress_predictions))

             precision    recall  f1-score   support

          0       0.86      0.85      0.86        80
          1       0.71      0.81      0.76        97
          2       0.81      0.80      0.80        99
          3       0.76      0.66      0.71        98
          4       0.86      0.78      0.82        96
          5       0.75      0.80      0.77        99
          6       0.72      0.86      0.78        98
          7       0.82      0.93      0.87        99
          8       0.91      0.86      0.89       100
          9       0.84      0.88      0.86        99
         10       0.91      0.92      0.92       100
         11       0.90      0.85      0.88        99
         12       0.83      0.84      0.83        98
         13       0.78      0.80      0.79        99
         14       0.87      0.89      0.88        99
         15       0.77      0.88      0.82       100
         16       0.82      0.88      0.85        91
         17       0.86      0.87      0.87   

In [20]:
#Confusion matrix. Higher values along the diagonal are better
print("Confusion matrix:\n%s" % confusion_matrix(y_test, logregress_predictions))

Confusion matrix:
[[68  0  0  0  0  0  0  0  0  1  0  1  0  1  0  4  0  2  0  3]
 [ 0 79  3  1  0  6  2  0  0  0  0  0  1  1  1  1  0  1  0  1]
 [ 0  5 79  4  1  5  2  0  1  0  0  0  1  0  1  0  0  0  0  0]
 [ 0  4  8 65  4  1  4  1  1  0  1  1  3  2  1  0  0  1  1  0]
 [ 0  3  1  8 75  1  3  0  0  0  0  0  2  0  0  1  1  1  0  0]
 [ 0  6  7  3  1 79  0  1  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  1 84  3  0  2  1  2  1  1  0  1  0  0  0  0]
 [ 0  1  0  0  0  0  2 92  0  0  0  0  1  2  1  0  0  0  0  0]
 [ 0  0  0  0  1  0  3  6 86  1  0  0  0  0  1  0  1  0  1  0]
 [ 0  1  0  1  0  1  2  0  0 87  4  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  3 92  0  0  0  0  0  0  0  1  0]
 [ 0  2  0  0  1  4  2  0  1  2  1 84  0  0  0  0  1  1  0  0]
 [ 0  5  0  2  1  1  2  4  0  0  0  0 82  0  1  0  0  0  0  0]
 [ 0  1  0  0  0  0  3  3  2  1  0  1  1 79  3  1  1  2  1  0]
 [ 1  1  0  0  1  2  2  0  0  0  0  0  0  3 88  1  0  0  0  0]
 [ 1  3  0  0  1  3  0  0  0  0  1  0

# Stochastic Gradient Descent

In [21]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', n_iter=5, n_jobs=1,
       penalty='l2', power_t=0.5, random_state=42, shuffle=True, verbose=0,
       warm_start=False)

In [22]:
sgd_predictions = sgd_clf.predict(X_test)

In [23]:
sgd_score = sgd_clf.score(X_test, y_test)
print(sgd_score)

0.872148541114


In [24]:
print(classification_report(y_test, sgd_predictions))

             precision    recall  f1-score   support

          0       0.87      0.85      0.86        80
          1       0.76      0.91      0.83        97
          2       0.82      0.87      0.84        99
          3       0.83      0.73      0.78        98
          4       0.88      0.84      0.86        96
          5       0.95      0.78      0.86        99
          6       0.77      0.91      0.84        98
          7       0.91      0.97      0.94        99
          8       0.97      0.92      0.94       100
          9       0.87      0.98      0.92        99
         10       0.98      0.98      0.98       100
         11       0.95      0.90      0.92        99
         12       0.92      0.82      0.86        98
         13       0.89      0.90      0.89        99
         14       0.89      0.94      0.92        99
         15       0.80      0.89      0.84       100
         16       0.89      0.92      0.91        91
         17       0.78      0.97      0.87   

In [25]:
print("Confusion matrix:\n%s" % confusion_matrix(y_test, sgd_predictions))

Confusion matrix:
[[68  0  0  0  0  0  0  0  0  1  0  1  0  0  0  3  0  2  0  5]
 [ 0 88  2  1  0  2  2  0  0  1  0  0  0  0  0  0  0  1  0  0]
 [ 0  5 86  2  2  1  2  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 1  4  5 72  5  0  5  0  1  0  0  0  2  0  2  0  0  1  0  0]
 [ 0  3  2  4 81  0  3  0  0  0  0  0  1  0  0  0  0  2  0  0]
 [ 0  4  8  4  1 77  0  0  0  2  0  0  0  0  1  0  0  2  0  0]
 [ 0  0  1  2  0  0 89  1  0  1  0  1  2  0  1  0  0  0  0  0]
 [ 0  2  0  0  0  0  0 96  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  4 92  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0 97  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  1 98  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  3  1  1  0  0 89  0  1  0  1  0  1  0  0]
 [ 0  3  0  2  2  0  4  3  0  0  0  1 80  1  2  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  0  1  0  0  0 89  1  1  0  4  1  0]
 [ 1  2  0  0  1  0  1  0  0  0  0  0  0  1 93  0  0  0  0  0]
 [ 3  2  0  0  0  1  1  0  0  1  0  0

# Scalable Vector Machine

In [26]:
from sklearn.svm import LinearSVC

scalable_vec_machine = LinearSVC(C=1, loss="hinge")
scalable_vec_machine.fit(X_train, y_train)

LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0)

In [27]:
svm_predictions = scalable_vec_machine.predict(X_test)

In [28]:
svn_score = scalable_vec_machine.score(X_test, y_test)
print(svn_score)

0.893899204244


In [29]:
print(classification_report(y_test, svm_predictions))

             precision    recall  f1-score   support

          0       0.84      0.88      0.86        80
          1       0.81      0.88      0.84        97
          2       0.83      0.87      0.85        99
          3       0.81      0.81      0.81        98
          4       0.93      0.86      0.90        96
          5       0.92      0.88      0.90        99
          6       0.84      0.89      0.87        98
          7       0.92      0.98      0.95        99
          8       0.97      0.95      0.96       100
          9       0.92      0.99      0.95        99
         10       0.96      0.99      0.98       100
         11       0.96      0.92      0.94        99
         12       0.91      0.86      0.88        98
         13       0.93      0.89      0.91        99
         14       0.93      0.94      0.93        99
         15       0.78      0.92      0.84       100
         16       0.90      0.95      0.92        91
         17       0.91      0.96      0.93   

In [30]:
print("Confusion matrix:\n%s" % confusion_matrix(y_test, svm_predictions))

Confusion matrix:
[[70  0  0  0  0  0  0  0  0  1  0  1  0  0  0  4  0  0  0  4]
 [ 0 85  2  1  0  4  2  0  0  1  0  0  1  0  0  0  0  1  0  0]
 [ 0  5 86  4  1  1  1  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  3  5 79  3  1  3  0  1  0  0  0  1  1  1  0  0  0  0  0]
 [ 0  3  2  4 83  0  0  0  0  0  1  0  1  0  0  0  0  2  0  0]
 [ 0  2  6  3  0 87  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  3  0  0 87  2  0  0  0  1  2  0  1  1  0  0  0  0]
 [ 0  1  0  1  0  0  0 97  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  2 95  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0 98  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1 99  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  3  0  1  0  0 91  0  0  1  1  0  1  0  0]
 [ 0  2  1  2  1  1  2  3  0  0  0  0 84  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  2  0  1  1  0  0 88  1  1  0  2  1  0]
 [ 1  1  0  0  1  0  1  0  1  0  0  0  0  1 93  0  0  0  0  0]
 [ 3  1  0  0  0  1  0  0  0  0  1  0

# Perceptron

In [32]:
from sklearn.linear_model import Perceptron

In [33]:
perceptron_clf = Perceptron()
perceptron_clf.fit(X_train, y_train)

Perceptron(alpha=0.0001, class_weight=None, eta0=1.0, fit_intercept=True,
      n_iter=5, n_jobs=1, penalty=None, random_state=0, shuffle=True,
      verbose=0, warm_start=False)

In [35]:
perceptron_predictions = perceptron_clf.predict(X_test)

In [36]:
perceptron_score = perceptron_clf.score(X_train, y_train)
print(perceptron_score)

0.98520134426


In [37]:
print(classification_report(y_test, perceptron_predictions))

             precision    recall  f1-score   support

          0       0.88      0.80      0.84        80
          1       0.87      0.80      0.83        97
          2       0.84      0.85      0.84        99
          3       0.74      0.74      0.74        98
          4       0.86      0.83      0.85        96
          5       0.89      0.80      0.84        99
          6       0.86      0.86      0.86        98
          7       0.90      0.94      0.92        99
          8       0.87      0.94      0.90       100
          9       0.94      0.93      0.93        99
         10       0.95      0.99      0.97       100
         11       0.99      0.80      0.88        99
         12       0.71      0.89      0.79        98
         13       0.98      0.83      0.90        99
         14       0.98      0.83      0.90        99
         15       0.95      0.81      0.88       100
         16       0.92      0.93      0.93        91
         17       0.95      0.96      0.95   

In [38]:
print("Confusion matrix:\n%s" % confusion_matrix(y_test, perceptron_predictions))

Confusion matrix:
[[64  0  0  0  0  0  0  0  0  1  0  1  0  0  0  1  0  0  1 12]
 [ 2 78  2  2  0  5  2  0  1  1  0  0  2  0  0  0  0  1  0  1]
 [ 0  5 84  6  2  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2 73  6  0  3  3  1  0  2  0  5  0  1  0  0  0  0  1]
 [ 0  1  2  7 80  1  0  0  1  0  0  0  4  0  0  0  0  0  0  0]
 [ 1  2  6  2  0 79  0  0  2  1  0  0  4  1  0  1  0  0  0  0]
 [ 0  0  0  4  2  1 84  1  1  0  0  0  4  0  0  0  0  0  0  1]
 [ 0  0  0  2  1  0  0 93  0  0  0  0  1  0  0  0  0  0  1  1]
 [ 0  0  0  0  0  0  0  2 94  2  0  0  1  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  1 92  3  0  1  0  0  0  1  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 99  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  1  0  0  3  0  2  0  0 79  4  0  0  0  1  0  5  4]
 [ 0  2  1  1  1  0  2  2  0  0  0  0 87  1  0  0  0  0  1  0]
 [ 0  0  1  0  0  0  3  2  0  0  0  0  2 82  0  0  0  1  4  4]
 [ 1  0  0  0  1  2  1  0  1  0  0  0  4  0 82  0  0  0  5  2]
 [ 1  1  1  0  0  1  0  0  1  0  0  0

# Citations

This experiment and notebook leverage libraries and packages made available through the scikit-learn project. Necessary citation is made here: Scikit-learn: Machine Learning in Python, Pedregosa et al., JMLR 12, pp. 2825-2830, 2011.